#!/usr/bin/env python3
#coding: utf-8
import smtplib
import os,sys
import time,datetime
import re

from email.mime.multipart import MIMEMultipart     #导入MIMEMultipart类
from email.mime.text import MIMEText               #导入  MIMEText
from email.mime.image import MIMEImage
from email.header import Header
from pydoc import serve

def sendemail():

    mail_host="smtp.gmail.com"  #设置服务器
    mail_user="linsheng@conew.com"    #用户名
    mail_pass="xxxxxxxxxxg"   #口令


    sender = 'linsheng@conew.com'
    receivers = ['linsheng@conew.com']                  #定义邮件发件人

    msgRoot = MIMEMultipart('related')
    subject = '性能测试数据邮件'
    msgRoot['Subject'] = Header(subject, 'utf-8')

    msgAlternative = MIMEMultipart('alternative')
    msgRoot.attach(msgAlternative)

    readfile(msgRoot)
    # 构造附件1，传送当前目录下的 test.txt 文件
    att1 = MIMEText(open('D:/work code/python/readdatawriteexcel/src/performance.xls', 'rb').read(), 'base64', 'utf-8')
    att1["Content-Type"] = 'application/octet-stream'
    # 这里的filename可以任意写，写什么名字，邮件中显示什么名字
    att1["Content-Disposition"] = 'attachment; filename="performance.xls"'
    msgRoot.attach(att1)

    # 构造附件2，传送当前目录下的 runoob.txt 文件
    att2 = MIMEText(open('D:/work code/python/readdatawriteexcel/src/readdate.py', 'rb').read(), 'base64', 'utf-8')
    att2["Content-Type"] = 'application/octet-stream'
    att2["Content-Disposition"] = 'attachment; filename="readdate.py"'
    msgRoot.attach(att2)

    try:
        smtpObj = smtplib.SMTP_SSL()
        smtpObj.connect(mail_host,  465)    # 25 为 SMTP 端口号
        smtpObj.login(mail_user,mail_pass)
        smtpObj.sendmail(mail_user, receivers, msgRoot.as_string())
        print "邮件发送成功"
    except smtplib.SMTPException, e:
        print "Error: 无法发送邮件" +str(e)
def readfile(msgRoot):
    i = 0
    for root ,dirs ,files in os.walk('D:/work code/python/readdatawriteexcel/src'):

        for filename in files:
            if filename.endswith('.png'):

                    mail_msg ="""
                    <br>
                    <br>
                    <br/>
                    <br/>
                    <br/>
                    <p><img src ='cid:image%s'></p>
                    """ % i
                    msgText = MIMEText('<img src="cid:image%s">' % i,'html','utf-8')
                    msgRoot.attach(msgText)
                    print str(filename)
                    # 指定图片为当前目录
                    fp = open('D:/work code/python/readdatawriteexcel/src/'+str(filename), 'rb')

                    print str(filename)
                    msgImage = MIMEImage(fp.read())
                    print fp
                    # 定义图片 ID，在 HTML 文本中引用
                    msgImage.add_header('Content-ID', '<image%s>' % i )
                    #print msgImage
                    msgRoot.attach(msgImage)
                    i+=1
                    fp.close()

# main
if __name__ == "__main__":
    sendemail()
